# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card.ui'
#
# Created: Wed Mar 28 08:40:35 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dati = QtWidgets.QTableWidget(self.centralwidget)
        self.dati.setGeometry(QtCore.QRect(310, 30, 461, 511))
        self.dati.setRowCount(32)
        self.dati.setColumnCount(8)
        self.dati.setObjectName("dati")
        self.dati.horizontalHeader().setVisible(True)
        self.dati.horizontalHeader().setCascadingSectionResizes(False)
        self.dati.horizontalHeader().setDefaultSectionSize(52)
        self.read = QtWidgets.QPushButton(self.centralwidget)
        self.read.setGeometry(QtCore.QRect(20, 470, 99, 27))
        self.read.setObjectName("read")
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(20, 430, 99, 27))
        self.connect.setObjectName("connect")
        self.disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect.setGeometry(QtCore.QRect(140, 430, 99, 27))
        self.disconnect.setObjectName("disconnect")
        self.unlock = QtWidgets.QPushButton(self.centralwidget)
        self.unlock.setGeometry(QtCore.QRect(140, 470, 99, 27))
        self.unlock.setObjectName("unlock")
        self.pin = QtWidgets.QLineEdit(self.centralwidget)
        self.pin.setGeometry(QtCore.QRect(20, 50, 71, 27))
        self.pin.setMaxLength(3)
        self.pin.setObjectName("pin")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 67, 17))
        self.label_4.setObjectName("label_4")
        self.card_status = QtWidgets.QLabel(self.centralwidget)
        self.card_status.setGeometry(QtCore.QRect(100, 40, 201, 41))
        self.card_status.setText("")
        self.card_status.setWordWrap(True)
        self.card_status.setObjectName("card_status")
        self.write = QtWidgets.QPushButton(self.centralwidget)
        self.write.setEnabled(False)
        self.write.setGeometry(QtCore.QRect(20, 510, 99, 27))
        self.write.setObjectName("write")
        self.change_pin = QtWidgets.QPushButton(self.centralwidget)
        self.change_pin.setEnabled(False)
        self.change_pin.setGeometry(QtCore.QRect(140, 510, 99, 27))
        self.change_pin.setObjectName("change_pin")
        self.bit_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_1.setGeometry(QtCore.QRect(20, 200, 21, 22))
        self.bit_1.setText("")
        self.bit_1.setObjectName("bit_1")
        self.bit_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_2.setGeometry(QtCore.QRect(40, 200, 21, 22))
        self.bit_2.setText("")
        self.bit_2.setObjectName("bit_2")
        self.bit_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_3.setGeometry(QtCore.QRect(60, 200, 21, 22))
        self.bit_3.setText("")
        self.bit_3.setObjectName("bit_3")
        self.bit_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_4.setGeometry(QtCore.QRect(80, 200, 21, 22))
        self.bit_4.setText("")
        self.bit_4.setObjectName("bit_4")
        self.bit_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_5.setGeometry(QtCore.QRect(100, 200, 21, 22))
        self.bit_5.setText("")
        self.bit_5.setObjectName("bit_5")
        self.bit_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_6.setGeometry(QtCore.QRect(120, 200, 21, 22))
        self.bit_6.setText("")
        self.bit_6.setObjectName("bit_6")
        self.bit_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_7.setGeometry(QtCore.QRect(140, 200, 21, 22))
        self.bit_7.setText("")
        self.bit_7.setObjectName("bit_7")
        self.bit_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_8.setGeometry(QtCore.QRect(160, 200, 21, 22))
        self.bit_8.setText("")
        self.bit_8.setObjectName("bit_8")
        self.bit_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_9.setGeometry(QtCore.QRect(20, 230, 21, 22))
        self.bit_9.setText("")
        self.bit_9.setObjectName("bit_9")
        self.bit_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_10.setGeometry(QtCore.QRect(40, 230, 21, 22))
        self.bit_10.setText("")
        self.bit_10.setObjectName("bit_10")
        self.bit_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_11.setGeometry(QtCore.QRect(60, 230, 21, 22))
        self.bit_11.setText("")
        self.bit_11.setObjectName("bit_11")
        self.bit_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_12.setGeometry(QtCore.QRect(80, 230, 21, 22))
        self.bit_12.setText("")
        self.bit_12.setObjectName("bit_12")
        self.bit_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_13.setGeometry(QtCore.QRect(100, 230, 21, 22))
        self.bit_13.setText("")
        self.bit_13.setObjectName("bit_13")
        self.bit_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_14.setGeometry(QtCore.QRect(120, 230, 21, 22))
        self.bit_14.setText("")
        self.bit_14.setObjectName("bit_14")
        self.bit_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_15.setGeometry(QtCore.QRect(140, 230, 21, 22))
        self.bit_15.setText("")
        self.bit_15.setObjectName("bit_15")
        self.bit_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_16.setGeometry(QtCore.QRect(160, 230, 21, 22))
        self.bit_16.setText("")
        self.bit_16.setObjectName("bit_16")
        self.bit_17 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_17.setGeometry(QtCore.QRect(20, 260, 21, 22))
        self.bit_17.setText("")
        self.bit_17.setObjectName("bit_17")
        self.bit_18 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_18.setGeometry(QtCore.QRect(40, 260, 21, 22))
        self.bit_18.setText("")
        self.bit_18.setObjectName("bit_18")
        self.bit_19 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_19.setGeometry(QtCore.QRect(60, 260, 21, 22))
        self.bit_19.setText("")
        self.bit_19.setObjectName("bit_19")
        self.bit_20 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_20.setGeometry(QtCore.QRect(80, 260, 21, 22))
        self.bit_20.setText("")
        self.bit_20.setObjectName("bit_20")
        self.bit_21 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_21.setGeometry(QtCore.QRect(100, 260, 21, 22))
        self.bit_21.setText("")
        self.bit_21.setObjectName("bit_21")
        self.bit_22 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_22.setGeometry(QtCore.QRect(120, 260, 21, 22))
        self.bit_22.setText("")
        self.bit_22.setObjectName("bit_22")
        self.bit_23 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_23.setGeometry(QtCore.QRect(140, 260, 21, 22))
        self.bit_23.setText("")
        self.bit_23.setObjectName("bit_23")
        self.bit_24 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_24.setGeometry(QtCore.QRect(160, 260, 21, 22))
        self.bit_24.setText("")
        self.bit_24.setObjectName("bit_24")
        self.bit_25 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_25.setGeometry(QtCore.QRect(20, 290, 21, 22))
        self.bit_25.setText("")
        self.bit_25.setObjectName("bit_25")
        self.bit_26 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_26.setGeometry(QtCore.QRect(40, 290, 21, 22))
        self.bit_26.setText("")
        self.bit_26.setObjectName("bit_26")
        self.bit_27 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_27.setGeometry(QtCore.QRect(60, 290, 21, 22))
        self.bit_27.setText("")
        self.bit_27.setObjectName("bit_27")
        self.bit_28 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_28.setGeometry(QtCore.QRect(80, 290, 21, 22))
        self.bit_28.setText("")
        self.bit_28.setObjectName("bit_28")
        self.bit_29 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_29.setGeometry(QtCore.QRect(100, 290, 21, 22))
        self.bit_29.setText("")
        self.bit_29.setObjectName("bit_29")
        self.bit_30 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_30.setGeometry(QtCore.QRect(120, 290, 21, 22))
        self.bit_30.setText("")
        self.bit_30.setObjectName("bit_30")
        self.bit_31 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_31.setGeometry(QtCore.QRect(140, 290, 21, 22))
        self.bit_31.setText("")
        self.bit_31.setObjectName("bit_31")
        self.bit_32 = QtWidgets.QCheckBox(self.centralwidget)
        self.bit_32.setGeometry(QtCore.QRect(160, 290, 21, 22))
        self.bit_32.setText("")
        self.bit_32.setObjectName("bit_32")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 170, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 16, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 16, 17))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 260, 16, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 290, 16, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 200, 16, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 230, 16, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 260, 16, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 290, 16, 17))
        self.label_10.setObjectName("label_10")
        self.protect_n = QtWidgets.QSpinBox(self.centralwidget)
        self.protect_n.setEnabled(False)
        self.protect_n.setGeometry(QtCore.QRect(220, 200, 51, 27))
        self.protect_n.setMinimum(1)
        self.protect_n.setMaximum(32)
        self.protect_n.setObjectName("protect_n")
        self.protect = QtWidgets.QPushButton(self.centralwidget)
        self.protect.setEnabled(False)
        self.protect.setGeometry(QtCore.QRect(210, 240, 81, 27))
        self.protect.setObjectName("protect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.read.setText(_translate("MainWindow", "Read", None))
        self.connect.setText(_translate("MainWindow", "Connect", None))
        self.disconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.unlock.setText(_translate("MainWindow", "Unlock", None))
        self.label_4.setText(_translate("MainWindow", "PIN", None))
        self.write.setText(_translate("MainWindow", "Write", None))
        self.change_pin.setText(_translate("MainWindow", "Change PIN", None))
        self.label.setText(_translate("MainWindow", "Protected Bytes", None))
        self.label_2.setText(_translate("MainWindow", "1", None))
        self.label_3.setText(_translate("MainWindow", "9", None))
        self.label_5.setText(_translate("MainWindow", "17", None))
        self.label_6.setText(_translate("MainWindow", "25", None))
        self.label_7.setText(_translate("MainWindow", "8", None))
        self.label_8.setText(_translate("MainWindow", "16", None))
        self.label_9.setText(_translate("MainWindow", "24", None))
        self.label_10.setText(_translate("MainWindow", "32", None))
        self.protect.setText(_translate("MainWindow", "Protect", None))
